<#
.SYNOPSIS
    Creates a basic Windows 10 Compliance Policy.
    
.DESCRIPTION
    Creates a policy requiring BitLocker and Secure Boot.
    Requires 'DeviceManagementConfiguration.ReadWrite.All' permission.

.NOTES
    File Name: 23_Create-CompliancePolicy_Windows.ps1
    Author: Kaffee & Code Assistant
    Version: 1.0
#>

param(
    [string]$PolicyName = "Win10_Basic_Security_Policy"
)

Connect-MgGraph -Scopes "DeviceManagementConfiguration.ReadWrite.All"

# Define Settings (Simplified)
$Params = @{
    "@odata.type" = "#microsoft.graph.windows10DeviceCompliancePolicy"
    displayName = $PolicyName
    description = "Generated by PowerShell. Requires BitLocker and Secure Boot."
    bitLockerEnabled = $true
    secureBootEnabled = $true
    passwordRequired = $true
    passwordMinimumLength = 6
}

try {
    New-MgDeviceManagementDeviceCompliancePolicy -BodyParameter $Params
    Write-Host "Compliance Policy '$PolicyName' created successfully." -ForegroundColor Green
} catch {
    Write-Error "Failed to create policy: $_"
}
